site_name: Nexus Button Documentation
site_url: https://thenexusavenger.github.io/Nexus-Button
repo_name: TheNexusAvenger/Nexus-Button
repo_url: https://github.com/TheNexusAvenger/Nexus-Button

theme:
  name: 'material'
  palette:
    primary: 'Blue'
    accent: 'Light Blue'

nav:
  - Home: index.md
  - Code Examples:
    - NexusButton: code-examples/nexusbutton.md
    - Factories: code-examples/factories.md

markdown_extensions:
  - admonition
  - codehilite