[package]
name = "thenexusavenger/nexus-button"
repository = "https://github.com/TheNexusAvenger/Nexus-Button"
description = "Multi-input button for Roblox to simplify UI development."
license = "MIT"
authors = ["TheNexusAvenger"]
version = "2.5.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "Packages", "Packages/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
NexusInstance = "thenexusavenger/nexus-instance@4.1.2"